name: SonarQube Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_HOST_URL: http://localhost:9000  # Change to the appropriate URL if using a different port or domain
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

