name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for SonarQube to be ready
        run: sleep 60  # Adjust the time based on how long it takes SonarQube to be ready

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-host-url: http://localhost:9000  # Change to the appropriate URL if using a different port or domain
          sonar-login: ${{ secrets.SONARQUBE_TOKEN }}
